controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    # create_reservation:
    #     path: '/api/reservation/create'
    #     methods: ['POST']
api_login_check:
    path: /api/login_check
nelmio_api_doc:
    resource: "@NelmioApiDocBundle/Resources/config/routing/swaggerui.xml"
